/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AtmPackage;

//import static java.lang.Class.forName;
//import java.sql.Connection;
//import java.sql.DriverManager;
//import java.sql.ResultSet;
//import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author ERIC
 */
public class LoginForm extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cardNoLab = new javax.swing.JLabel();
        logInButt = new javax.swing.JButton();
        cancelButt = new javax.swing.JButton();
        cardNOInsrt = new javax.swing.JTextField();
        loginLeb = new javax.swing.JLabel();
        paswrdInsrt = new javax.swing.JPasswordField();
        RegButt = new javax.swing.JButton();
        passwrdLab = new javax.swing.JLabel();
        logTypComb = new javax.swing.JComboBox<>();
        lock = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 153));

        cardNoLab.setBackground(new java.awt.Color(204, 204, 0));
        cardNoLab.setFont(new java.awt.Font("Yu Gothic UI Semilight", 3, 14)); // NOI18N
        cardNoLab.setForeground(new java.awt.Color(204, 0, 0));
        cardNoLab.setText("CardNO");

        logInButt.setBackground(new java.awt.Color(255, 255, 153));
        logInButt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AtmPackag/images/icons8-login-24.png"))); // NOI18N
        logInButt.setText("Login");
        logInButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logInButtActionPerformed(evt);
            }
        });

        cancelButt.setBackground(new java.awt.Color(255, 255, 153));
        cancelButt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AtmPackag/images/icons8-cancel-24.png"))); // NOI18N
        cancelButt.setText("Cancel");
        cancelButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtActionPerformed(evt);
            }
        });

        loginLeb.setFont(new java.awt.Font("Cambria Math", 2, 24)); // NOI18N
        loginLeb.setText("Login");

        paswrdInsrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paswrdInsrtActionPerformed(evt);
            }
        });
        paswrdInsrt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                paswrdInsrtKeyPressed(evt);
            }
        });

        RegButt.setText("Register");
        RegButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegButtActionPerformed(evt);
            }
        });

        passwrdLab.setFont(new java.awt.Font("Yu Gothic UI Semilight", 3, 14)); // NOI18N
        passwrdLab.setForeground(new java.awt.Color(204, 0, 0));
        passwrdLab.setText("PinCode");

        logTypComb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Client", "Admin" }));
        logTypComb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logTypCombActionPerformed(evt);
            }
        });

        lock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AtmPackag/images/icons8-password-50.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(loginLeb, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lock)
                        .addGap(51, 51, 51))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(cardNoLab, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(passwrdLab, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(logInButt)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(102, 251, Short.MAX_VALUE)
                                .addComponent(RegButt))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(paswrdInsrt, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                                    .addComponent(cardNOInsrt, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                                    .addComponent(logTypComb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancelButt)
                        .addGap(27, 27, 27))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RegButt)
                    .addComponent(lock, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginLeb, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cardNoLab, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardNOInsrt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paswrdInsrt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwrdLab, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(logTypComb, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButt)
                    .addComponent(logInButt))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtActionPerformed
        // TODO add your handling code here:
        //cardNOInsrt.setText("");
        //cardNOInsrt.setText("");
        dispose();
        
    }//GEN-LAST:event_cancelButtActionPerformed

    private void logInButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logInButtActionPerformed
        // TODO add your handling code here:
        // login code
//        String url = "jdbc:mysql://localhost:3306/king";
//        String username = "root";
//        String Password = "king360";
//        Connection connection;


          Operations operation = new Operations();
        try{
            //open connections
            //Class.forName("com.mysql.jdbc.Driver");
            
            
            String cardId = cardNOInsrt.getText();
            String pinCode = paswrdInsrt.getText();
            String userType = logTypComb.getSelectedItem().toString();
            
            if (Operations.isLogin(cardId, pinCode, userType, this)){
                new MainManue().setVisible(true);
                this.dispose();
                
                
                //0754673870
            }else if(cardId.equals("2334") && pinCode.equals("10100") && userType == "Admin" ){
                    new ATMSystem().setVisible(true);
                    this.dispose();
              
            }else{ 
            
            
//            
     
//            connection = DriverManager.getConnection(url, username, Password);
//            
//            
//            String cardNumbr = cardNOInsrt.getText();
//            String password = paswrdInsrt.getText();
//            
//            Statement statement = connection.createStatement();
//            //mysql Query to run
//            
//           String sql = "select*from employees where last_name = '" +cardNumbr + "' and id = '" + password + "'";
//           ResultSet rs = statement.executeQuery(sql);
//           if(rs.next()){
//               // if card number and password are true the continue
//               
//               dispose();//close login page
//               MainManue mainManue = new MainManue();
//               mainManue.show();       }else{
               //if cardNo and password are wrong the show message
               
               
               JOptionPane.showMessageDialog(this, " Card number or password is wrong..");
               cardNOInsrt.setText("");
               paswrdInsrt.setText("");
           }
//          connection.close();
            
        } catch(Exception e){
            System.out.println("Error in connections");
        }
    }//GEN-LAST:event_logInButtActionPerformed

    private void RegButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegButtActionPerformed
        // TODO add your handling code here:
        dispose();
        RegestrationForm regForm = new RegestrationForm();
        regForm.show();
    }//GEN-LAST:event_RegButtActionPerformed

    private void paswrdInsrtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_paswrdInsrtKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_paswrdInsrtKeyPressed

    private void paswrdInsrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paswrdInsrtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paswrdInsrtActionPerformed

    private void logTypCombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logTypCombActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logTypCombActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RegButt;
    private javax.swing.JButton cancelButt;
    private javax.swing.JTextField cardNOInsrt;
    private javax.swing.JLabel cardNoLab;
    private javax.swing.JLabel lock;
    private javax.swing.JButton logInButt;
    private javax.swing.JComboBox<String> logTypComb;
    private javax.swing.JLabel loginLeb;
    private javax.swing.JLabel passwrdLab;
    private javax.swing.JPasswordField paswrdInsrt;
    // End of variables declaration//GEN-END:variables
}
